apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-control-plane
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-control-plane
  template:
    metadata:
      labels:
        app: devops-control-plane
    spec:
      containers:
        - name: devops-control-plane
          image: devops-control-plane:latest
          ports:
            - containerPort: 8080
