apiVersion: v1
kind: Service
metadata:
  name: devops-control-plane
  namespace: default
spec:
  selector:
    app: devops-control-plane
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
